# Generated by Django 3.1.7 on 2021-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileControlRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.PositiveSmallIntegerField(default=1, verbose_name='Tipo de registro')),
                ('NIT', models.CharField(max_length=13, verbose_name='NIT')),
                ('entity_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de entidad recaudadora')),
                ('agreement_code', models.CharField(max_length=15, verbose_name='Código del convenio')),
                ('transmission_date', models.DateField(verbose_name='Fecha de transmisión del archivo')),
                ('tracking_number', models.CharField(max_length=1, verbose_name='Secuencia de envío')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('register_number', models.IntegerField(verbose_name='Número de registros')),
                ('total_transaction_value', models.FloatField(verbose_name='Valor total de las transacciones')),
            ],
            options={
                'verbose_name': 'Registro de control de archivo',
                'verbose_name_plural': 'Registros de control de archivo',
            },
        ),
        migrations.CreateModel(
            name='RegisterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.PositiveSmallIntegerField(default=6, verbose_name='Tipo de registro')),
                ('client_id', models.CharField(blank=True, max_length=13, null=True, verbose_name='NIT del pagador')),
                ('client_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre del pagador')),
                ('bank_account', models.CharField(blank=True, max_length=9, null=True, verbose_name='Cuenta bancaria del pagador')),
                ('bank_account_number', models.CharField(blank=True, max_length=17, null=True, verbose_name='Número de la cuenta a debitar')),
                ('transaction_type', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo de transacción')),
                ('transaction_value', models.FloatField(verbose_name='Valor de la transacción')),
                ('validation_indicator', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='Indicador validación NIT/CTA')),
                ('reference1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Referencia 1')),
                ('reference2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Referencia 2')),
                ('expiration_date', models.DateField(null=True, verbose_name='Fecha de vencimiento')),
                ('billed_period', models.CharField(blank=True, max_length=2, null=True, verbose_name='Periodos facturados')),
                ('cycle', models.CharField(blank=True, max_length=3, null=True, verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Detalle de registros de cobros',
                'verbose_name_plural': 'Detalle de registros de cobros',
            },
        ),
    ]
