# Generated by Django 3.1.7 on 2021-03-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_to_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filecontrolrecord',
            unique_together={('NIT', 'transmission_date', 'tracking_number')},
        ),
    ]
